// match-pair-content-vn-entj.ts
// Task 4 retone — BATCH 3: 14 cặp ENTJ+*
// Content agent · 16/06/2026 · giữ pairKey/texture/coverage/tag nguồn
// compat-only (cachDiQua rỗng): ENTJ+ENTJ, ENTJ+ENTP, ENTJ+INTJ, ENTJ+INTP — giữ nguyên cấu trúc
// Sửa lỗi lẫn type: ENTJ+INFP (gốc lẫn ENTP/ESFJ)

import type { MatchPairContent } from './match-pair-content'

export const MATCH_PAIR_CONTENT_VN_ENTJ: Record<string, MatchPairContent> = {
  'ENTJ+ENTJ': {
    pairKey: 'ENTJ+ENTJ',
    tenCap: 'Hai thủ lĩnh',
    texture: 'challenge_pair',
    dongLuc: 'Hiểu nhau về tham vọng và hiệu quả — nhưng ai sẽ nhường trong tranh luận?',
    vungDeHop: 'Cả hai đều thúc đẩy kết quả và tôn trọng năng lực — không ai nuông chiều ai.',
    vungMaSat: 'Cả hai đều muốn kiểm soát và muốn thắng — tranh giành quyền chủ động là rủi ro lớn nhất.',
    canDeY: [
      'Thống nhất ngay từ đầu: trong một mối quan hệ, không có tranh luận để "thắng" — chỉ có cùng tìm giải pháp tốt hơn.',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTJ+ENTP': {
    pairKey: 'ENTJ+ENTP',
    tenCap: 'Sắc bén cùng nhau',
    texture: 'growth_pair',
    dongLuc: 'Cùng yêu tranh luận, cùng tư duy chiến lược — ENTP mang sự hỗn loạn sáng tạo; ENTJ mang khả năng triển khai tập trung.',
    vungDeHop: 'Rất hợp về mặt trí tuệ — không ai thấy người kia nhàm, không ai ngại bị thách thức.',
    vungMaSat: 'Tranh luận không bao giờ dừng — cần biết khi nào nên gật đầu và đi tiếp.',
    canDeY: [
      'Đặt quy tắc: sau 20 phút tranh luận không tới đâu → tung đồng xu, hoặc thử một cách rồi đánh giá.',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTJ+ESFJ': {
    pairKey: 'ENTJ+ESFJ',
    tenCap: 'Khác cơ bản',
    texture: 'challenge_pair',
    dongLuc: 'ENTJ thiên về logic và hướng tới tương lai; ESFJ thiên về con người và hòa khí — khác nhau nhiều về giá trị.',
    vungDeHop: 'ESFJ mang sự ấm áp ENTJ thiếu; ENTJ mang định hướng ESFJ cần.',
    vungMaSat: 'ENTJ có thể lấn át cảm xúc của ESFJ; ESFJ có thể né va chạm nhiều hơn mức ENTJ chịu được. ENTJ tập trung logic và kết quả; ESFJ tập trung con người và hòa khí — hai cách xử lý quyết định rất khác nhau.',
    canDeY: [
      'ENTJ: nói nhẹ hơn, công nhận tác động lên người khác.',
      'ESFJ: tập nói thẳng điều mình không đồng ý.',
      'Sự thẳng thắn của ENTJ làm tổn thương ESFJ vốn cần hòa thuận.',
      'Nhu cầu đồng thuận của ESFJ làm chậm nhịp của ENTJ.',
    ],
    cachDiQua: [
      'ENTJ: Coi mối lo về con người của ESFJ là một rủi ro thật cho cả công việc lẫn mối quan hệ — không phải mềm yếu, đó là dữ liệu thật.',
      'ESFJ: Trình bày nỗi lo kèm ví dụ cụ thể — ENTJ tiếp nhận tốt hơn với cách nói rõ ràng.',
      'Cả hai: ENTJ triển khai + ESFJ ấm áp = một tổ chức và một mái nhà mà người ta muốn thuộc về.',
    ],
    funFact: 'ENTJ và ESFJ đều hướng ngoại và thích sự dứt khoát — cùng năng lượng và cùng muốn chốt việc tạo nên sự hợp ý bất ngờ về cấu trúc. [S]',
    coverage: 'full',
  },
  'ENTJ+ESFP': {
    pairKey: 'ENTJ+ESFP',
    tenCap: 'Khó tìm chung',
    texture: 'challenge_pair',
    dongLuc: 'ENTJ tính chiến lược dài hạn; ESFP vui với khoảnh khắc hiện tại — khác nhau về tầm nhìn thời gian và ưu tiên.',
    vungDeHop: 'ESFP giúp ENTJ tận hưởng cuộc sống hơn; ENTJ giúp ESFP tính cho tương lai.',
    vungMaSat: 'ENTJ thấy ESFP thiếu nghiêm túc; ESFP thấy ENTJ quá căng. ENTJ hướng tương lai và nghiêm túc; ESFP sống hiện tại và đặt niềm vui lên trước — hai định hướng sống khác nhau.',
    canDeY: [
      'Tìm một hoạt động chung không cần thống nhất lối sống — đi du lịch, cùng xây dựng cái gì đó.',
      'Sự tự phát của ESFP phá vỡ kế hoạch của ENTJ.',
      'Sự nghiêm túc của ENTJ làm tắt niềm vui của ESFP.',
    ],
    cachDiQua: [
      'ENTJ: Đôi khi nhập cuộc niềm vui hiện tại của ESFP — cuộc sống cũng cần được trải nghiệm, không chỉ được lên kế hoạch.',
      'ESFP: Tham gia vào kế hoạch dài hạn của ENTJ — sự góp mặt của bạn giúp nó thành hiện thực tốt hơn.',
      'Cả hai: ENTJ dựng nền móng; ESFP lấp đầy nó bằng niềm vui.',
    ],
    funFact: 'ENTJ và ESFP đều hướng ngoại và nhiều năng lượng — hợp về cường độ nhưng đi theo hai hướng rất khác. [S]',
    coverage: 'full',
  },
  'ENTJ+ESTJ': {
    pairKey: 'ENTJ+ESTJ',
    tenCap: 'Cùng hướng đi',
    texture: 'growth_pair',
    dongLuc: 'Cùng nhóm dứt khoát — cùng coi trọng hiệu quả và kết quả — nhưng ENTJ thiên chiến lược hơn, ESTJ thiên vận hành hơn.',
    vungDeHop: 'Hiểu nhau về cam kết và trách nhiệm — đáng tin với nhau.',
    vungMaSat: 'Cả hai đều cứng — bất đồng dễ leo thang vì không ai muốn lùi. Cả hai đều quen dẫn dắt; khi cách làm khác nhau, cả hai đều chắc chắn cách mình là đúng.',
    canDeY: [
      'Đặt quy tắc: khi bất đồng về một quyết định quan trọng, cả hai trình bày lý lẽ, nếu hòa thì tung đồng xu.',
      'Cả hai đều muốn là người ra quyết định.',
      'Cách xoay chiến lược của ENTJ va với cách làm theo hệ thống của ESTJ.',
    ],
    cachDiQua: [
      'ENTJ: Tôn trọng chuyên môn vận hành của ESTJ — tầm nhìn của bạn cần kỹ năng thực thi của họ.',
      'ESTJ: Tham gia vào tầm nhìn chiến lược của ENTJ — kế hoạch của bạn tốt hơn khi nhìn bức tranh lớn hơn.',
      'Cả hai: Bạn lo chiến lược (ENTJ), họ lo vận hành (ESTJ) — một sự bổ sung thật khi cả hai cùng công nhận.',
    ],
    funFact: 'ENTJ và ESTJ đều có tư duy hướng ngoại dẫn đầu — cùng định hướng hiệu quả và tôn trọng năng lực. Sự nể nhau đến tự nhiên ngay từ đầu. [S]',
    coverage: 'full',
  },
  'ENTJ+ESTP': {
    pairKey: 'ENTJ+ESTP',
    tenCap: 'Hành động cộng hưởng',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều dứt khoát và hướng kết quả — dễ nể nhau về năng lực.',
    vungDeHop: 'Cùng tiến nhanh, không ai làm chậm người kia — một mối quan hệ đầy năng lượng.',
    vungMaSat: 'ENTJ tính kế hoạch dài hạn; ESTP hành động ngắn hạn — căng nhau về tốc độ và hướng đi. Cả hai đều dứt khoát và ưa hành động — dễ va nhau về ai dẫn và cách nào đúng.',
    canDeY: [
      'ENTJ: để ESTP lo phần triển khai tức thời.',
      'ESTP: tin vào tầm nhìn xa hơn của ENTJ.',
      'Cả hai đều muốn phụ trách.',
      'Sự ứng biến của ESTP va với cách thực thi có cấu trúc của ENTJ.',
    ],
    cachDiQua: [
      'ENTJ: Sự linh hoạt chiến thuật của ESTP thường giúp cải thiện chiến lược — để họ tùy biến trong khâu thực thi.',
      'ESTP: Kế hoạch dài hạn của ENTJ giúp tránh những vòng phản ứng tốn kém.',
      'Cả hai: Mỗi người lo một tầm nhìn thời gian — chiến lược (ENTJ) và chiến thuật (ESTP). Hãy tận dụng điều đó.',
    ],
    funFact: 'ENTJ và ESTP đều có tư duy và giác quan hướng ngoại dẫn đầu — định hướng hành động cao nhất trong các cặp. Họ nể năng lực của nhau ngay tức thì. [S]',
    coverage: 'full',
  },
  'ENTJ+INFJ': {
    pairKey: 'ENTJ+INFJ',
    tenCap: 'Chiều sâu gặp tầm nhìn',
    texture: 'golden_pair',
    dongLuc: 'Chiều sâu và sự thấu suốt của INFJ bổ sung hoàn hảo với khả năng triển khai của ENTJ — cả hai đều nghĩ dài hạn.',
    vungDeHop: 'INFJ giúp ENTJ kết nối với yếu tố con người; ENTJ giúp INFJ biến tầm nhìn thành hiện thực.',
    vungMaSat: 'Sự thẳng thắn của ENTJ có thể làm INFJ tổn thương; nhu cầu hòa khí của INFJ va với sự bộc trực của ENTJ. ENTJ thúc quyết định nhanh; INFJ cần thời gian để xử lý và cảm cho đúng hướng — lệch nhau về tốc độ.',
    canDeY: [
      'ENTJ: đưa lời phê bình kèm sự tế nhị.',
      'INFJ: đừng coi sự thẳng thắn của ENTJ là công kích cá nhân.',
      'ENTJ phê bình thẳng → INFJ thấy bị tấn công.',
      'INFJ cần được thấu hiểu sâu → ENTJ không hiểu vì sao cần điều đó.',
    ],
    cachDiQua: [
      'ENTJ: Cho INFJ một hạn rõ nhưng chừa thời gian suy nghĩ trước đó — "Mình cần câu trả lời trước [ngày], bạn ngẫm giúp nhé?"',
      'INFJ: Khi sự thẳng thắn của ENTJ nghe gắt, nhớ đó là vì hiệu quả, không phải lạnh lùng — hỏi "Bạn đang chê ý tưởng hay chê tôi?"',
      'Cả hai: Tầm nhìn của INFJ + khả năng triển khai của ENTJ = rất mạnh — đừng để khác biệt phong cách chặn việc hợp tác.',
    ],
    funFact: 'ENTJ và INFJ đều có trực giác hướng nội dẫn đầu — cả hai đều nghĩ dài hạn, chỉ là ENTJ thực thi quyết liệt còn INFJ ngẫm sâu. [S]',
    coverage: 'full',
  },
  'ENTJ+INFP': {
    pairKey: 'ENTJ+INFP',
    tenCap: 'Khác ngôn ngữ',
    texture: 'challenge_pair',
    dongLuc: 'ENTJ thiên logic và hiệu quả; INFP thiên giá trị và sự chân thật — như nói hai ngôn ngữ khác nhau về cuộc sống.',
    vungDeHop: 'INFP mang chiều sâu cảm xúc ENTJ thiếu; ENTJ mang định hướng INFP cần.',
    vungMaSat: 'ENTJ có thể lấn át INFP; INFP có thể không nói rõ nhu cầu của mình — dễ thành một thế lệch nếu không để ý. ENTJ thiên logic và kết quả; INFP thiên giá trị và ý nghĩa — đôi khi thấy nhau thiếu đúng cái mình cần nhất.',
    canDeY: [
      'ENTJ: hỏi ý kiến INFP và thật sự lắng nghe trước khi quyết.',
      'INFP: tập nói thẳng nhu cầu của mình.',
      'ENTJ quyết nhanh, áp đặt → INFP thấy giá trị của mình bị bỏ qua.', // [SỬA LỖI LẪN TYPE: gốc "ENTP… → ESFJ…"]
      'INFP cần xử lý nội tâm trước → ENTJ sốt ruột vì muốn quyết ngay.', // [SỬA LỖI LẪN TYPE: gốc "ESFJ… → ENTP…"]
    ],
    cachDiQua: [
      'ENTJ: Khi INFP nêu mối lo về giá trị, coi đó là dữ liệu hợp lệ — "Điều này tác động gì đến con người?" là một câu hỏi chiến lược, không phải mềm yếu.',
      'INFP: Nói thẳng nhu cầu — ENTJ cần lời đề nghị rõ ràng, cụ thể để đáp lại hiệu quả. "Mình cần bạn lắng nghe 5 phút" tốt hơn sự im lặng.',
      'Cả hai: Kết quả mong muốn thường giống nhau — ENTJ muốn thành quả, INFP muốn ý nghĩa. Khi đồng thuận về "vì sao", phần "làm thế nào" dễ hơn.',
    ],
    funFact: 'ENTJ và INFP đều có niềm tin mạnh mẽ — ENTJ về chiến lược, INFP về giá trị. Khi đồng điệu, cặp này tạo ra hiệu quả vừa có tác động vừa có chiều sâu. [P]',
    coverage: 'full',
  },
  'ENTJ+INTJ': {
    pairKey: 'ENTJ+INTJ',
    tenCap: 'Chiến lược đồng thuận',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều có tầm nhìn và tư duy chiến lược — nể nhau về năng lực và tham vọng.',
    vungDeHop: 'Một cặp đầy sức mạnh — cùng xây và cùng đạt, hiểu nhu cầu độc lập của nhau.',
    vungMaSat: 'Cả hai đều cứng đầu và không giỏi cảm xúc — mối quan hệ dễ trở nên quá "việc nào ra việc nấy", thiếu hơi ấm.',
    canDeY: [
      'Sắp lịch cho khoảng thời gian "không năng suất" — ở bên nhau mà không có mục tiêu gì, chỉ là ở bên nhau.',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTJ+INTP': {
    pairKey: 'ENTJ+INTP',
    tenCap: 'Lý trí cùng nhịp',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều coi trọng năng lực và chiều sâu trí tuệ — nể nhau từ sớm.',
    vungDeHop: 'INTP đưa ra phân tích sâu; ENTJ đưa ra định hướng — một đội tốt cả trong lẫn ngoài mối quan hệ.',
    vungMaSat: 'Cả hai đều không tự nhiên về cảm xúc — mối quan hệ dễ thiếu hơi ấm nếu không chủ động.',
    canDeY: [
      'Chủ động bày tỏ sự trân trọng và quan tâm — đừng cho rằng người kia tự biết.',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTJ+ISFJ': {
    pairKey: 'ENTJ+ISFJ',
    tenCap: 'Cần nhiều nỗ lực',
    texture: 'challenge_pair',
    dongLuc: 'ENTJ luôn đẩy giới hạn; ISFJ gìn giữ nề nếp — va nhau về tốc độ và cách sống.',
    vungDeHop: 'ISFJ mang sự chăm sóc và ổn định; ENTJ mang tầm nhìn và động lực — ổn định nếu biết tôn trọng nhau.',
    vungMaSat: 'ENTJ có thể vô tình lấn át nhu cầu của ISFJ; ISFJ có thể thấy quá tải. ENTJ đẩy nhanh và mạnh; ISFJ cần sự ấm áp và ổn định — tốc độ và phong cách va nhau thường xuyên.',
    canDeY: [
      'ENTJ: chậm lại và hỏi trước khi quyết.',
      'ISFJ: lên tiếng sớm, đừng chờ đến lúc bực.',
      'Cường độ của ENTJ áp đảo ISFJ nhẹ nhàng.',
      'Nhịp của ISFJ làm ENTJ vốn ưa hành động thấy nản.',
    ],
    cachDiQua: [
      'ENTJ: Nhẹ nhịp hơn khi ở cạnh ISFJ — cách nói thẳng có thể gây tổn thương ngoài ý muốn.',
      'ISFJ: Nói ra sớm khi thấy quá tải — ENTJ đáp lại lời nói rõ ràng, không phải ám chỉ.',
      'Cả hai: Động lực của ENTJ + sự chăm sóc của ISFJ = một tổ chức và một mái nhà mà cả hai cùng đạt được và cùng nuôi dưỡng.',
    ],
    funFact: 'ENTJ và ISFJ đều thuộc nhóm dứt khoát — sự đáng tin và theo việc đến cùng tạo nền tin tưởng ngầm dù phong cách khác nhau. [S]',
    coverage: 'full',
  },
  'ENTJ+ISFP': {
    pairKey: 'ENTJ+ISFP',
    tenCap: 'Khác biệt lớn',
    texture: 'challenge_pair',
    dongLuc: 'ENTJ mạnh mẽ và có hệ thống; ISFP dịu dàng và sống theo giá trị — rất ít điểm chung tự nhiên.',
    vungDeHop: 'ISFP mang sự chân thật và chất nghệ ENTJ ngưỡng mộ; ENTJ mang cấu trúc ISFP được lợi.',
    vungMaSat: 'Tốc độ và cường độ của ENTJ dễ làm ISFP quá tải; sự rút lui của ISFP dễ làm ENTJ bực. ENTJ có hệ thống và quả quyết; ISFP dịu dàng và theo giá trị — phong cách của ENTJ có thể nghe như lấn át.',
    canDeY: [
      'ENTJ: bắt nhịp với ISFP khi không phải lúc tập trung vào việc.',
      'ISFP: nói rõ những ranh giới mình cần.',
      'ENTJ lấn át sự phản kháng nhẹ nhàng của ISFP.',
      'Cách sống theo giá trị của ISFP nghe thiếu thực tế với ENTJ.',
    ],
    cachDiQua: [
      'ENTJ: Những phản đối nhẹ nhàng về giá trị của ISFP là dữ liệu thật — hỏi rõ "Điều gì khiến bạn lo?"',
      'ISFP: Nói nỗi lo một lần, rõ và thẳng — ENTJ đáp lại lời nói rõ ràng.',
      'Cả hai: ENTJ triển khai + ISFP chân thật = những thứ vừa chạy được vừa thật.',
    ],
    funFact: 'ENTJ và ISFP có cách phán đoán đối nghịch nhau — và chính điều mỗi người ưu tiên lại khiến người kia tò mò thật sự. [S]',
    coverage: 'full',
  },
  'ENTJ+ISTJ': {
    pairKey: 'ENTJ+ISTJ',
    tenCap: 'Kỷ luật chung',
    texture: 'growth_pair',
    dongLuc: 'Cùng nhóm dứt khoát và lý trí — cùng coi trọng cấu trúc và kết quả — ENTJ thiên tầm nhìn, ISTJ thiên vận hành.',
    vungDeHop: 'Sự đáng tin và cam kết từ cả hai — một nền móng chắc cho mối quan hệ lâu dài.',
    vungMaSat: 'Cả hai đều không giỏi bày tỏ cảm xúc — mối quan hệ cần chủ động thêm hơi ấm. ENTJ thiên chiến lược và đổi mới; ISTJ thiên hệ thống và cái đã được kiểm chứng — căng nhau giữa thay đổi và ổn định.',
    canDeY: [
      'Đặt một "buổi hỏi han cảm xúc" mỗi tuần — không phải về vấn đề, chỉ là mỗi người đang thấy thế nào.',
      'ENTJ muốn nghĩ lại cái ISTJ đã tối ưu.',
      'Cả hai cùng cứng về cách làm.',
    ],
    cachDiQua: [
      'ENTJ: Ghi nhận điều đang chạy tốt trước khi đề xuất thay đổi — ISTJ cần biết bạn trân trọng nền móng họ xây.',
      'ISTJ: Tham gia vào tầm nhìn chiến lược của ENTJ — phần thực thi của bạn tốt hơn khi có bối cảnh rộng hơn.',
      'Cả hai: ENTJ đưa định hướng; ISTJ đưa khâu triển khai đáng tin. Vai trò rõ ràng giúp giảm va chạm.',
    ],
    funFact: 'ENTJ và ISTJ đều thuộc nhóm lý trí và dứt khoát — cùng tôn trọng năng lực và kết quả. Sự nể nhau đến tự nhiên. [S]',
    coverage: 'full',
  },
  'ENTJ+ISTP': {
    pairKey: 'ENTJ+ISTP',
    tenCap: 'Tôn trọng nhau',
    texture: 'challenge_pair',
    dongLuc: 'Cả hai đều giỏi và độc lập — nể nhau nhưng không tự nhiên gần gũi.',
    vungDeHop: 'ISTP không bị ENTJ áp đảo — nể nhau như những người ngang hàng, không trên dưới.',
    vungMaSat: 'Cả hai đều ít bày tỏ cảm xúc — thiếu hơi ấm có thể khiến mối quan hệ thấy lạnh. ENTJ lên kế hoạch chiến lược; ISTP ứng biến chiến thuật — va nhau về cách làm dù cùng giỏi.',
    canDeY: [
      'Tìm một thử thách hoặc dự án chung — gắn kết qua việc làm là hiệu quả nhất với cả hai.',
      'Kế hoạch tỉ mỉ của ENTJ va với phong cách ứng biến của ISTP.',
      'Không ai tự nhiên bày tỏ cảm xúc.',
    ],
    cachDiQua: [
      'ENTJ: Tin vào khả năng xử lý tức thời của ISTP — sự linh hoạt của họ lo được phần kế hoạch bỏ sót.',
      'ISTP: Báo trước cho ENTJ khi lệch khỏi kế hoạch — một câu là đủ.',
      'Cả hai: Cả hai đều rất giỏi — sự nể nhau qua năng lực thể hiện được là rất chắc.',
    ],
    funFact: 'ENTJ và ISTP đều thiên lý trí — cùng một khung tư duy logic tạo sự nể nhau về trí tuệ một cách tự nhiên. Họ hiểu cách nghĩ của nhau. [S]',
    coverage: 'full',
  },
}
