// match-pair-content-vn-enfj.ts
// Task 4 retone — BATCH 1: 16 cặp ENFJ+* viết lại tiếng Việt sạch
// Content agent · 16/06/2026 17:30 · làm mẫu chất lượng + template cho 120 cặp còn lại
// Đã: bỏ EN code-mixing · sửa 3 lỗi lẫn type (ENFJ+ISFJ/ISFP/ISTP) · giữ pairKey/texture/coverage/tag nguồn
// ⚠️ File gốc auto-generated — bản này để MA đối chiếu/duyệt tone trước khi quyết PATH 1 vs PATH 2 (xem QA report)

import type { MatchPairContent } from './match-pair-content'

export const MATCH_PAIR_CONTENT_VN_ENFJ: Record<string, MatchPairContent> = {
  'ENFJ+ENFJ': {
    pairKey: 'ENFJ+ENFJ',
    tenCap: 'Hai trái tim',
    texture: 'growth_pair',
    dongLuc: 'Hiểu nhau sâu sắc về nhu cầu kết nối và ý nghĩa — nhưng không ai đủ thực tế để lo phần mặt đất.',
    vungDeHop: 'Cùng tần số về giá trị, cùng đặt con người lên trên hết, cuộc trò chuyện không bao giờ cạn.',
    vungMaSat: 'Hai người cùng muốn cho — ai sẽ nhận? Dễ rơi vào kiệt sức khi cả hai đều rút cạn năng lượng để phục vụ nhau.',
    canDeY: [
      'Lên lịch "thời gian chỉ để nhận" — hôm đó không ai phải là người chăm sóc.',
      'Cả hai đều muốn lo liệu cho người kia — rồi ai sẽ theo kế hoạch của ai?',
      'Khi một người quá tải, người kia gánh thêm và cũng quá tải theo.',
    ],
    cachDiQua: [
      'ENFJ (người A): Cho phép mình được nhận sự chăm sóc — nói ra khi bạn cần được đỡ, thay vì chỉ đỡ người kia.',
      'ENFJ (người B): Tương tự — học cách nhờ giúp thay vì mặc định người kia luôn ổn.',
      'Cả hai: Tạo một nếp "chỉ để nhận" — mỗi tuần một ngày, người này chăm, người kia chỉ nhận, không phải lo đáp lại.',
    ],
    funFact: 'ENFJ là nhóm có xu hướng kiệt sức cao khi yêu, vì hay đặt người kia lên trước bản thân quá mức. [P]',
    coverage: 'full',
  },
  'ENFJ+ENFP': {
    pairKey: 'ENFJ+ENFP',
    tenCap: 'Bùng cháy cùng',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều sống bằng cảm xúc và ý nghĩa — ENFJ mang cấu trúc, ENFP mang sự tự phát.',
    vungDeHop: 'Năng lượng cộng hưởng cực mạnh, cùng quan tâm đến thế giới và con người xung quanh.',
    vungMaSat: 'ENFJ cần kế hoạch và theo sát đến cùng; ENFP muốn tự phát và linh hoạt — dễ va nhau về cam kết và lịch trình.',
    canDeY: [
      'Thống nhất trước: phần nào cần có kế hoạch, phần nào để tự phát.',
      'ENFP hủy hẹn phút chót → ENFJ thấy như mình không được tôn trọng.',
      'ENFJ thúc ép cam kết → ENFP thấy bị áp lực và rút lui.',
    ],
    cachDiQua: [
      'ENFJ: Cho ENFP thấy vì sao kế hoạch quan trọng — không phải vì bạn muốn kiểm soát, mà vì bạn cần đoán trước để lo cho người khác.',
      'ENFP: Khi đã đồng ý một kế hoạch, hãy coi đó là cam kết thật — hủy hẹn của ENFJ gây hụt hẫng lớn hơn bạn nghĩ.',
      'Cả hai: Chia rõ "vùng linh hoạt" và "vùng cam kết" — có việc cần kế hoạch, có việc cứ để tự nhiên.',
    ],
    funFact: 'ENFJ và ENFP thường tìm thấy nhau vì cả hai đều hiếm trong dân số (~3% mỗi nhóm) và cùng coi trọng chiều sâu kết nối. [P]',
    coverage: 'full',
  },
  'ENFJ+ENTJ': {
    pairKey: 'ENFJ+ENTJ',
    tenCap: 'Lãnh đạo đôi',
    texture: 'growth_pair',
    dongLuc: 'Cùng sức hút và tham vọng — nhưng ENFJ dẫn bằng trái tim, ENTJ dẫn bằng chiến lược.',
    vungDeHop: 'Cặp này tạo được tác động lớn khi cùng mục tiêu — bổ sung giữa trái tim và lý trí.',
    vungMaSat: 'Hai người cùng quen dẫn dắt trong một mối quan hệ — ai lùi khi cần? Dễ cạnh tranh quyền chủ động.',
    canDeY: [
      'Xác định rõ lĩnh vực của mỗi người — không phải việc nào cũng cần một người dẫn.',
      'ENTJ gạt đi nỗi lo cảm xúc → ENFJ thấy mình không được lắng nghe.',
      'ENFJ muốn cả hai đồng thuận → ENTJ muốn quyết nhanh rồi đi tiếp.',
    ],
    cachDiQua: [
      'ENFJ: Khi không đồng ý với ENTJ, hãy đóng khung nỗi lo của bạn bằng dữ liệu và tác động — ENTJ tiếp nhận lý lẽ tốt hơn cảm xúc đơn thuần.',
      'ENTJ: Hãy công nhận mối lo về con người của ENFJ là dữ liệu hợp lệ, không phải "mềm yếu". Sức khỏe của mối quan hệ cũng là một biến số chiến lược.',
      'Cả hai: Thống nhất trước ai dẫn ở lĩnh vực nào — tránh tranh vai trò dẫn dắt trên cùng một quyết định.',
    ],
    funFact: 'ENFJ và ENTJ cùng có chức năng cảm xúc hướng ngoại và tư duy hướng ngoại — cả hai đều muốn tác động lên môi trường, nhưng qua hai góc khác nhau. [S]',
    coverage: 'full',
  },
  'ENFJ+ENTP': {
    pairKey: 'ENFJ+ENTP',
    tenCap: 'Tim và Óc',
    texture: 'growth_pair',
    dongLuc: 'ENFJ cảm nhận trước; ENTP phân tích trước — kết hợp lại cho một góc nhìn đầy đủ hơn.',
    vungDeHop: 'ENTP kích thích ENFJ tư duy sắc bén hơn; ENFJ giúp ENTP kết nối với cảm xúc người khác.',
    vungMaSat: 'ENTP tranh luận để khám phá ý tưởng; ENFJ đôi khi thấy giá trị của mình bị thách thức như chuyện cá nhân.',
    canDeY: [
      'ENTP: báo trước "tôi đang phản biện cho vui, không phải chê bạn." ENFJ: hỏi ý định trước khi phòng thủ.',
      'ENTP tranh luận đùa về điều ENFJ coi trọng sâu sắc → ENFJ tổn thương.',
      'ENFJ muốn giữ hòa khí → ENTP thấy đó là dập tắt thảo luận thẳng thắn.',
    ],
    cachDiQua: [
      'ENFJ: Phân biệt ENTP đang tranh luận ý tưởng hay đang công kích con người — thường là vế trước. Hỏi thẳng "Bạn đang khám phá hay thật sự phản đối?"',
      'ENTP: Ra dấu rõ khi bạn đang đóng vai phản biện — ENFJ cần biết bạn đang nghĩ thành tiếng, không phải phán xét.',
      'Cả hai: Tranh luận là cách ENTP thể hiện sự tôn trọng — họ chỉ tranh luận với người họ thấy đáng về mặt trí tuệ.',
    ],
    funFact: 'ENFJ và ENTP đều có chức năng hướng ngoại dẫn đầu (một bên cảm xúc, một bên ý tưởng) — tạo nên một nhịp tương tác rất sôi nổi. [S]',
    coverage: 'full',
  },
  'ENFJ+ESFJ': {
    pairKey: 'ENFJ+ESFJ',
    tenCap: 'Ấm áp đôi',
    texture: 'growth_pair',
    dongLuc: 'Chia sẻ giá trị về con người và sự hòa hợp — cùng muốn tạo ra môi trường tốt cho người xung quanh.',
    vungDeHop: 'Ngôi nhà của cặp này luôn ấm áp và chào đón. Hiểu nhau về nhu cầu kết nối sâu.',
    vungMaSat: 'Cả hai đều hay chiều lòng người khác — va chạm thật dễ bị dìm quá lâu vì cả hai đều tránh phá vỡ hòa khí.',
    canDeY: [
      'Đặt một buổi "nói thẳng" định kỳ — không gian an toàn để nói điều khó trước khi quá muộn.',
      'Cả hai cùng né va chạm → vấn đề nhỏ tích lại thành lớn.',
      'ENFJ muốn thay đổi → ESFJ thích sự ổn định và cách đã được kiểm chứng.',
    ],
    cachDiQua: [
      'ENFJ: Bạn nhìn bức tranh lớn rõ hơn ESFJ — khi thấy vấn đề đang tích tụ, bạn cần là người mở lời thẳng thắn trước.',
      'ESFJ: Tin vào tầm nhìn dài hạn của ENFJ — khi họ muốn đổi cái đang chạy ổn, thường là có lý do cho tương lai.',
      'Cả hai: Cam kết nói thật khi khó chịu — đóng khung kiểu "tôi chia sẻ vì tôi quan tâm, không phải để chỉ trích."',
    ],
    funFact: 'ENFJ và ESFJ đều có cảm xúc hướng ngoại dẫn đầu — đây là một trong những cặp nhạy với hòa khí xã giao nhất. [S]',
    coverage: 'full',
  },
  'ENFJ+ESFP': {
    pairKey: 'ENFJ+ESFP',
    tenCap: 'Sâu và Rực',
    texture: 'growth_pair',
    dongLuc: 'ENFJ mang chiều sâu ý nghĩa; ESFP mang niềm vui hiện tại — cùng hướng ngoại và yêu con người.',
    vungDeHop: 'ESFP kéo ENFJ ra khỏi việc suy nghĩ quá đà; ENFJ giúp ESFP tìm thêm ý nghĩa trong cuộc sống.',
    vungMaSat: 'ENFJ cần cam kết và theo sát đến cùng; ESFP sống trong hiện tại và ít tính xa — dễ làm nhau bực về lịch trình.',
    canDeY: [
      'ESFP: cho ENFJ biết kế hoạch sớm hơn một chút.',
      'ENFJ: để một số thứ không cần kế hoạch.',
      'ESFP không theo kế hoạch → ENFJ thấy mình không được tôn trọng.',
      'ENFJ hướng về tương lai → ESFP muốn tận hưởng hiện tại.',
    ],
    cachDiQua: [
      'ENFJ: Trân trọng sự tự phát của ESFP như một món quà, không phải sự vô trách nhiệm. Tận hưởng khoảnh khắc thay vì lúc nào cũng lo bước kế tiếp.',
      'ESFP: Khi ENFJ lên kế hoạch cho bạn, đó là một cách họ quan tâm — hãy tham gia với hứng thú thật, dù không phải phong cách của bạn.',
      'Cả hai: Phân định rõ thời gian có cấu trúc và thời gian thả lỏng — đừng để một người luôn phải chiều theo nhịp người kia.',
    ],
    funFact: 'ENFJ và ESFP đều hướng ngoại và lấy con người làm trọng tâm — sự hợp ý về mặt xã giao thường rất tốt ngay từ đầu. [P]',
    coverage: 'full',
  },
  'ENFJ+ESTJ': {
    pairKey: 'ENFJ+ESTJ',
    tenCap: 'Khác nhịp',
    texture: 'challenge_pair',
    dongLuc: 'Cùng thích có cấu trúc, nhưng cách ra quyết định rất khác — ENFJ dùng cảm xúc, ESTJ dùng logic.',
    vungDeHop: 'ESTJ mang khả năng triển khai và sự đáng tin; ENFJ mang sự ấm áp và kết nối con người — bổ sung tốt nếu biết tôn trọng nhau.',
    vungMaSat: 'ENFJ ra quyết định qua cảm xúc và tác động lên con người; ESTJ qua logic và quy trình — hai cách thường cho kết quả khác nhau.',
    canDeY: [
      'ESTJ: công nhận cảm xúc trước khi đưa ra giải pháp.',
      'ENFJ: nêu lo ngại kèm dữ liệu khi cần.',
      'ESTJ gạt đi cảm xúc → ENFJ thấy mình không được nghe.',
      'ENFJ muốn bàn về cảm xúc lâu → ESTJ muốn chuyển sang hành động.',
    ],
    cachDiQua: [
      'ENFJ: Khi muốn ESTJ cân nhắc yếu tố cảm xúc, hãy trình bày như dữ liệu: "Tinh thần cả nhóm đang đi xuống vì X — đây là một rủi ro cụ thể."',
      'ESTJ: Công nhận nỗi lo cảm xúc trước khi nhảy vào giải pháp — "Tôi nghe bạn, và tôi muốn cùng tìm cách ổn cho cả hai phía."',
      'Cả hai: Quyết định tốt nhất khi có cả dữ liệu lẫn tác động lên con người — mỗi người đại diện cho một phía quan trọng.',
    ],
    funFact: 'ENFJ và ESTJ đều thuộc nhóm thích sự dứt khoát — họ hiểu nhau về nhu cầu chốt việc và cam kết, dù đường đến đó rất khác. [S]',
    coverage: 'full',
  },
  'ENFJ+ESTP': {
    pairKey: 'ENFJ+ESTP',
    tenCap: 'Khám phá nhau',
    texture: 'challenge_pair',
    dongLuc: 'ENFJ sống vì ý nghĩa tương lai; ESTP sống vì trải nghiệm hiện tại — hai cách nhìn đời rất khác.',
    vungDeHop: 'ESTP kéo ENFJ vào khoảnh khắc hiện tại; ENFJ giúp ESTP nhìn xa hơn.',
    vungMaSat: 'ENFJ sống vì ý nghĩa và kết nối; ESTP sống vì hành động và trải nghiệm — rất khác nhau về điều khiến đời thấy "đủ đầy".',
    canDeY: [
      'Tìm hoạt động cả hai cùng hứng thú, thay vì cố đổi nhịp sống của nhau.',
      'ESTP nói thẳng → ENFJ tổn thương sâu.',
      'ENFJ cần cuộc trò chuyện cảm xúc dài → ESTP muốn giải quyết nhanh rồi tiếp tục.',
    ],
    cachDiQua: [
      'ENFJ: Thỉnh thoảng nhập cuộc hành động cùng ESTP — bạn sẽ thấy kết nối có thể đến qua việc làm chung, không chỉ qua trò chuyện.',
      'ESTP: ENFJ cần nói về cảm xúc và ý nghĩa — không phải vì họ nghĩ ngợi quá, mà vì đó là cách họ kết nối.',
      'Cả hai: Tìm một hoạt động nơi cả hai thấy mình sống động — một cuộc phiêu lưu, rồi một cuộc trò chuyện sâu sau đó.',
    ],
    funFact: 'ENFJ và ESTP đối lập ở nhiều mặt nhưng cùng quan tâm đến con người — ENFJ qua sự thấu cảm, ESTP qua việc giúp đỡ thiết thực. [P]',
    coverage: 'full',
  },
  'ENFJ+INFJ': {
    pairKey: 'ENFJ+INFJ',
    tenCap: 'Tâm hồn đồng điệu',
    texture: 'golden_pair',
    dongLuc: 'ENFJ và INFJ chia sẻ cùng những chức năng nhận thức theo thứ tự khác nhau — hiểu nhau không cần giải thích.',
    vungDeHop: 'Kết nối sâu nhất trong các cặp — cùng giá trị, cùng cách nhìn thế giới qua lăng kính ý nghĩa.',
    vungMaSat: 'Cả hai đều gánh cảm xúc của người khác sâu sắc — khi va chạm, cả hai có thể cùng chìm vào quá tải.',
    canDeY: [
      'Dành thời gian nạp lại riêng — không phải mọi thứ đều cần xử lý cùng nhau ngay lập tức.',
      'INFJ cần thời gian một mình → ENFJ lo lắng và cần được trấn an.',
      'ENFJ tạo nhiều ràng buộc xã giao → INFJ kiệt sức.',
    ],
    cachDiQua: [
      'ENFJ: Cho INFJ không gian để xử lý một mình — đừng hiểu sự im lặng đó là bị chối từ.',
      'INFJ: Nói trước khi bạn cần nạp lại, để ENFJ không lo lắng rồi đòi kết nối nhiều hơn.',
      'Cả hai: Khi cùng quá tải một lúc, thống nhất dừng lại — "mình cần 30 phút, rồi quay lại."',
    ],
    funFact: 'ENFJ và INFJ là phản chiếu của nhau trong cấu trúc chức năng — đây là lý do họ hiểu nhau sâu đến mức gần như không cần giải thích. [S]',
    coverage: 'full',
  },
  'ENFJ+INFP': {
    pairKey: 'ENFJ+INFP',
    tenCap: 'Bổ sung lý tưởng',
    texture: 'golden_pair',
    dongLuc: 'ENFJ mang năng lượng và sự tổ chức; INFP mang chiều sâu và sự chân thật — bổ sung tự nhiên.',
    vungDeHop: 'ENFJ giúp INFP kết nối với thế giới; INFP giúp ENFJ chậm lại và đi sâu hơn vào nội tâm.',
    vungMaSat: 'ENFJ muốn kế hoạch và hành động; INFP cần xử lý bên trong trước khi quyết — dễ lệch nhịp.',
    canDeY: [
      'ENFJ: đừng lấp kín mọi cuối tuần bằng lịch bận rộn.',
      'INFP: nói khi cần nạp lại, trước khi kiệt sức.',
      'ENFJ xếp quá nhiều việc xã giao → INFP cần thời gian một mình để hồi lại.',
      'INFP rút vào im lặng → ENFJ lo lắng và đòi kết nối.',
    ],
    cachDiQua: [
      'ENFJ: Cho INFP thời gian để xử lý — thúc ép quyết định quá nhanh sẽ tạo ra sự phản kháng.',
      'INFP: Nói rõ mốc thời gian — "Cho mình mấy hôm để nghĩ" — thay vì im lặng rồi rút lui.',
      'Cả hai: Cả hai đều quan tâm sâu sắc — khi va chạm, nhắc lại điều đó cho nhau nhớ.',
    ],
    funFact: 'ENFJ và INFP thường tìm thấy nhau vì cả hai đều thuộc nhóm hiếm (2-3% dân số mỗi nhóm) và cùng coi trọng chiều sâu kết nối. [P]',
    coverage: 'full',
  },
  'ENFJ+INTJ': {
    pairKey: 'ENFJ+INTJ',
    tenCap: 'Đối cực hút nhau',
    texture: 'growth_pair',
    dongLuc: 'ENFJ bị hút bởi chiều sâu của INTJ; INTJ bị hút bởi sự ấm áp của ENFJ — khác biệt tạo nên sức hút.',
    vungDeHop: 'ENFJ giúp INTJ kết nối với cảm xúc người khác; INTJ giúp ENFJ tư duy chiến lược hơn.',
    vungMaSat: 'ENFJ cần được công nhận và kết nối thường xuyên; INTJ thể hiện quan tâm qua hành động hơn lời nói — lệch nhau về cách bày tỏ.',
    canDeY: [
      'Lập một nếp "hỏi han ngắn" mỗi ngày — đủ để ENFJ thấy được kết nối mà không làm INTJ cạn sức.',
      'INTJ im lặng → ENFJ lo lắng và cần được trấn an.',
      'ENFJ cần nhiều giao tiếp xã hội → INTJ cần ở một mình sau khi giao tiếp.',
    ],
    cachDiQua: [
      'ENFJ: Học nhận ra hành động của INTJ chính là tình yêu — khi họ giải quyết vấn đề giúp bạn, đó là cách họ nói "tôi thương bạn".',
      'INTJ: Tập nói thành lời "tôi trân trọng bạn" hoặc "tôi quan tâm" — ENFJ cần nghe, không chỉ nhìn thấy.',
      'Cả hai: Liệt kê rõ những hành động thể hiện quan tâm cụ thể — giúp INTJ biết ENFJ cần gì, giúp ENFJ hiểu INTJ không hề lạnh lùng.',
    ],
    funFact: 'ENFJ và INTJ thường hút nhau: ENFJ thấy INTJ thú vị và bí ẩn, INTJ thấy ENFJ ấm áp và cuốn hút. [P]',
    coverage: 'full',
  },
  'ENFJ+INTP': {
    pairKey: 'ENFJ+INTP',
    tenCap: 'Thế giới khác nhau',
    texture: 'growth_pair',
    dongLuc: 'ENFJ sống bằng cảm xúc và con người; INTP sống bằng ý tưởng và logic — ít điểm chung tự nhiên.',
    vungDeHop: 'Khi kết hợp được: INTP đưa ra phân tích, ENFJ đưa ra sự thấu cảm — quyết định tốt hơn.',
    vungMaSat: 'ENFJ xử lý qua con người và trò chuyện; INTP xử lý qua việc suy nghĩ một mình — khi va chạm, mỗi người cần điều kiện ngược nhau để ổn lại.',
    canDeY: [
      'Học ngôn ngữ của nhau: ENFJ nói "tôi cần bạn lắng nghe"; INTP nói "tôi đang phân tích, không phải bác bỏ."',
      'INTP phân tích khi ENFJ cần chỗ dựa cảm xúc.',
      'ENFJ muốn nói chuyện ngay → INTP cần thời gian một mình để nghĩ trước.',
    ],
    cachDiQua: [
      'ENFJ: Cho INTP thời gian suy nghĩ trước khi bàn — "Mình muốn nói về X, khi nào bạn sẵn sàng thì báo."',
      'INTP: Khi ENFJ cần kết nối cảm xúc, họ không cần bạn "sửa" gì — thử chỉ lắng nghe và nói "mình nghe bạn."',
      'Cả hai: Thống nhất cách xử lý: INTP cần thời gian nghĩ, ENFJ cần thời gian nói — sắp lịch cho cả hai.',
    ],
    funFact: 'ENFJ và INTP cùng có những chức năng giúp nối ý tưởng từ nhiều lĩnh vực — khiến cuộc trò chuyện của họ rất phong phú. [S]',
    coverage: 'full',
  },
  'ENFJ+ISFJ': {
    pairKey: 'ENFJ+ISFJ',
    tenCap: 'Chăm sóc lẫn nhau',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều đặt người khác lên đầu và muốn tạo ra môi trường an toàn — cùng một ngôn ngữ yêu thương.',
    vungDeHop: 'Sự ấm áp và quan tâm của cả hai tạo nên một mối quan hệ bền vững và nuôi dưỡng.',
    vungMaSat: 'Cả hai đều quan tâm và đều né va chạm — vấn đề dễ tích tụ vì không ai muốn làm người kia buồn.',
    canDeY: [
      'Tạo một buổi "nói thật an toàn" định kỳ — cam kết nói thẳng dù khó.',
      'Cả hai cùng tránh va chạm → vấn đề âm thầm lớn dần.',
      'ISFJ giữ lo lắng trong lòng → ENFJ phải đoán điều chưa được nói ra.', // [SỬA LỖI LẪN TYPE: gốc ghi "INTP phân tích lạnh lùng"]
    ],
    cachDiQua: [
      'ENFJ: Là người mở lời thẳng thắn trước — bạn dễ chịu với việc đối diện hơn ISFJ, nên hãy nhận vai dẫn dắt.',
      'ISFJ: Tin rằng sự chia sẻ thẳng thắn của ENFJ xuất phát từ quan tâm, không phải chỉ trích — nói ra nỗi lo sớm.',
      'Cả hai: "Tôi nói điều này vì muốn chúng ta tốt hơn" — đóng khung mọi cuộc nói chuyện khó qua lăng kính quan tâm.',
    ],
    funFact: 'ENFJ và ISFJ đều có cảm xúc hướng ngoại dẫn đầu — vì thế cả hai cực kỳ nhạy với bầu không khí cảm xúc xung quanh. [S]',
    coverage: 'full',
  },
  'ENFJ+ISFP': {
    pairKey: 'ENFJ+ISFP',
    tenCap: 'Nhẹ nhàng hòa quyện',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều quan tâm và sống theo giá trị — ENFJ biểu lộ nhiều hơn, ISFP trầm hơn nhưng cùng chiều sâu.',
    vungDeHop: 'ISFP giúp ENFJ chậm lại và trân trọng hiện tại; ENFJ giúp ISFP kết nối với thế giới rộng hơn.',
    vungMaSat: 'ENFJ hướng ngoại và hay bày tỏ; ISFP hướng nội và trầm lặng — ENFJ có thể không nhận ra ISFP đang cần khoảng riêng.',
    canDeY: [
      'ENFJ: hỏi trước thay vì mặc định.',
      'ISFP: nói ra nhu cầu thay vì lặng lẽ rút lui.',
      'ENFJ nói thẳng về vấn đề → ISFP thấy bị phán xét và rút lui.', // [SỬA LỖI LẪN TYPE: gốc ghi "ENTJ… → INFP…"]
      'ISFP lặng lẽ rút lui → ENFJ lo lắng và thúc thêm.',
    ],
    cachDiQua: [
      'ENFJ: Hỏi han thường xuyên: "Bạn cần khoảng riêng hay cần kết nối lúc này?" — đừng tự mặc định.',
      'ISFP: Nói khi bạn cần ở một mình, thay vì chỉ rút lui — ENFJ sẽ lo nếu không được cho biết.',
      'Cả hai: ISFP yêu qua sự hiện diện lặng lẽ và hành động; ENFJ yêu qua lời nói và sự lo liệu — cả hai đều hợp lệ.',
    ],
    funFact: 'ENFJ và ISFP có cách hướng tới giá trị khác chiều — một bên hướng ra hòa khí bên ngoài, một bên hướng vào giá trị bên trong — nhưng cả hai đều quan tâm sâu sắc. [S]',
    coverage: 'full',
  },
  'ENFJ+ISTJ': {
    pairKey: 'ENFJ+ISTJ',
    tenCap: 'Đất và Mây',
    texture: 'challenge_pair',
    dongLuc: 'ENFJ sống vì cảm xúc và khả năng; ISTJ sống vì thực tế và trách nhiệm — ít điểm chồng lấn.',
    vungDeHop: 'ISTJ mang sự ổn định và đáng tin; ENFJ mang sự ấm áp — cặp này cân bằng được nếu biết tôn trọng nhau.',
    vungMaSat: 'ENFJ linh hoạt và hướng về tương lai; ISTJ quy củ và coi trọng cách cũ đã quen — dễ va nhau về tốc độ thay đổi.',
    canDeY: [
      'Tìm những giá trị chung (gia đình, trách nhiệm) làm nền, thay vì xoáy vào khác biệt.',
      'ENFJ muốn đổi cách làm → ISTJ cần bằng chứng trước khi thay đổi.',
      'ISTJ chú trọng quy trình → ENFJ thấy yếu tố con người bị bỏ qua.',
    ],
    cachDiQua: [
      'ENFJ: Trình bày đề xuất thay đổi kèm bằng chứng cụ thể — ISTJ cần lý do đã được kiểm chứng, không phải chỉ "hãy tin tôi".',
      'ISTJ: Khi ENFJ muốn đổi điều đang chạy ổn, hãy hỏi lý do trước khi gạt đi — thường có điều bạn chưa thấy.',
      'Cả hai: Tôn trọng rằng ổn định và phát triển đều cần thiết — mỗi người đại diện cho một nhu cầu quan trọng.',
    ],
    funFact: 'ENFJ và ISTJ đều thuộc nhóm thích sự dứt khoát — họ hiểu nhau về cam kết và theo việc đến cùng, dù đường đến đó rất khác. [S]',
    coverage: 'full',
  },
  'ENFJ+ISTP': {
    pairKey: 'ENFJ+ISTP',
    tenCap: 'Tìm đường qua nhau',
    texture: 'challenge_pair',
    dongLuc: 'ENFJ cần kết nối cảm xúc sâu; ISTP cần tự do và ít kịch tính — hai nhu cầu nền tảng khó hòa.',
    vungDeHop: 'ISTP giúp ENFJ thực tế và vững chân hơn; ENFJ giúp ISTP để ý tới đời sống cảm xúc.',
    vungMaSat: 'ENFJ cần kết nối cảm xúc và lời khẳng định; ISTP thể hiện quan tâm qua giúp đỡ thiết thực và ít nói — lệch lớn về cách bày tỏ.',
    canDeY: [
      'Lập ngôn ngữ chung: ISTP nói "tôi ổn, chỉ cần xử lý một mình"; ENFJ nói "tôi cần kết nối, không phải lời giải."',
      'ISTP không nói ra cảm xúc → ENFJ thấy bị mất kết nối.',
      'ISTP cần xử lý một mình → ENFJ muốn nói chuyện ngay để kết nối.', // [SỬA LỖI LẪN TYPE: gốc ghi "INFP… → ENTJ…"]
    ],
    cachDiQua: [
      'ENFJ: Nhận ra việc ISTP sửa giúp bạn chính là "tôi thương bạn" — đừng chỉ chờ lời nói.',
      'ISTP: Tập nói ra điều bạn trân trọng — đôi khi ENFJ cần nghe "mình thế này là vì bạn."',
      'Cả hai: Vẽ rõ cách mỗi người thể hiện quan tâm — để cả hai biết cách cho và nhận theo đúng kiểu người kia cần.',
    ],
    funFact: 'ENFJ và ISTP có cấu trúc chức năng gần như ngược nhau — điều này tạo sức hút ban đầu mạnh và khả năng cùng trưởng thành sâu. [S]',
    coverage: 'full',
  },
}
