// match-pair-content-vn-entp.ts
// Task 4 retone — BATCH 4: 13 cặp ENTP+*
// Content agent · 16/06/2026 · giữ pairKey/texture/coverage/tag nguồn
// compat-only: ENTP+ENTP, ENTP+INTJ, ENTP+INTP · Sửa lỗi lẫn type: ENTP+INFP (gốc lẫn ESFP/INTJ)

import type { MatchPairContent } from './match-pair-content'

export const MATCH_PAIR_CONTENT_VN_ENTP: Record<string, MatchPairContent> = {
  'ENTP+ENTP': {
    pairKey: 'ENTP+ENTP',
    tenCap: 'Không ngừng kích thích',
    texture: 'growth_pair',
    dongLuc: 'Hiểu nhau hoàn toàn về tình yêu với tranh luận và ý tưởng — nhưng ai sẽ là người bắt tay vào làm?',
    vungDeHop: 'Không bao giờ chán — trò chuyện và ý tưởng không bao giờ dừng.',
    vungMaSat: 'Cả hai đều tranh luận đủ thứ — có thể mệt và khó đi đến quyết định.',
    canDeY: [
      'Thống nhất một "vùng không tranh luận" — vài chủ đề được miễn khỏi việc tranh cãi.',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTP+ESFJ': {
    pairKey: 'ENTP+ESFJ',
    tenCap: 'Khó tìm tiếng chung',
    texture: 'challenge_pair',
    dongLuc: 'ENTP thách thức mọi thứ; ESFJ coi trọng hòa khí và nề nếp — căng thẳng nền tảng.',
    vungDeHop: 'ESFJ mang sự ấm áp và khéo léo xã giao; ENTP mang sự kích thích trí tuệ.',
    vungMaSat: 'Lối phản biện của ENTP dễ làm ESFJ tổn thương; nhu cầu hòa khí của ESFJ làm ENTP bực. ENTP thách thức mọi thứ kể cả nề nếp ESFJ coi trọng — nghe như thiếu tôn trọng dù không cố ý.',
    canDeY: [
      'ENTP: phân biệt khi nào bạn tranh luận cho vui và khi nào thật sự bất đồng.',
      'ESFJ: hiểu rằng tranh luận không phải chuyện cá nhân.',
      'ENTP tranh luận về những điều ESFJ trân trọng như một bài tập trí tuệ.',
      'Nhu cầu hòa thuận của ESFJ làm ENTP đang đi tìm sự thật thấy nản.',
    ],
    cachDiQua: [
      'ENTP: Báo hiệu khi bạn tranh luận cho vui so với khi thật sự thách thức — ESFJ dễ tổn thương.',
      'ESFJ: Tranh luận của ENTP là cách họ tham gia nghiêm túc — không phải để công kích bạn.',
      'Cả hai: Sự ấm áp của ESFJ + ý tưởng của ENTP = một cộng đồng vừa chào đón vừa sống động về trí tuệ.',
    ],
    funFact: 'ENTP và ESFJ đều hướng ngoại — năng lượng xã hội cao tạo kết nối ban đầu ngay cả khi phong cách khác nhau nhiều. [S]',
    coverage: 'full',
  },
  'ENTP+ESFP': {
    pairKey: 'ENTP+ESFP',
    tenCap: 'Năng lượng cao',
    texture: 'challenge_pair',
    dongLuc: 'Cả hai đều tự phát và vui — dễ có khoảng thời gian vui vẻ cùng nhau.',
    vungDeHop: 'ESFP mang niềm vui và hành động; ENTP mang ý tưởng và chiều sâu — cân bằng tốt.',
    vungMaSat: 'ENTP cần chiều sâu trí tuệ; ESFP thích vui bề mặt — lệch nhau về điều gì làm kết nối có ý nghĩa. ENTP cần chiều sâu trí tuệ; ESFP cần niềm vui xã hội — hai định nghĩa khác nhau về một khoảng thời gian vui.',
    canDeY: [
      'Tìm hoạt động kết hợp hành động và bàn luận — trò chơi, đi du lịch kèm chuyện trò.',
      'ESFP thấy cường độ trí tuệ của ENTP mệt mỏi.',
      'ENTP thấy niềm vui bề mặt của ESFP không đủ.',
    ],
    cachDiQua: [
      'ENTP: Đôi khi nhập cuộc thế giới xã hội của ESFP — con người thật thú vị hơn bạn nghĩ.',
      'ESFP: Tham gia một chủ đề sâu của ENTP — có thể thú vị hơn bạn tưởng.',
      'Cả hai: Những cuộc phiêu lưu kèm bàn luận sau đó — hoạt động của ESFP, phần tìm ý nghĩa của ENTP.',
    ],
    funFact: 'ENTP và ESFP đều hướng ngoại — năng lượng xã hội cao tạo kết nối ban đầu tự nhiên. Khoảng cách về chiều sâu là điều cần xử lý lâu dài. [S]',
    coverage: 'full',
  },
  'ENTP+ESTJ': {
    pairKey: 'ENTP+ESTJ',
    tenCap: 'Tranh luận mãi',
    texture: 'challenge_pair',
    dongLuc: 'Cả hai đều bộc trực và nhiều chính kiến — nhưng ENTP ưa cái mơ hồ, ESTJ muốn chốt.',
    vungDeHop: 'ESTJ mang khả năng triển khai thực tế; ENTP mang tư duy đổi mới — kỹ năng bổ sung nhau.',
    vungMaSat: 'ESTJ thấy ENTP coi thường quy tắc; ENTP thấy ESTJ quá cứng. ENTP ưa cái mơ hồ; ESTJ muốn chốt — căng nhau liên tục về khi nào một quyết định là cuối cùng.',
    canDeY: [
      'ENTP: chọn quy tắc nào đáng thách thức.',
      'ESTJ: thử một ý tưởng "điên" của ENTP và xem chuyện gì xảy ra.',
      'ENTP vẫn tranh luận sau khi ESTJ đã quyết.',
      'Sự cứng nhắc của ESTJ cản trở khâu khám phá ENTP cần.',
    ],
    cachDiQua: [
      'ENTP: Tôn trọng thời điểm chốt của ESTJ — sau khi họ quyết, tiếp tục tranh luận gây hại.',
      'ESTJ: Cho ENTP thời gian khám phá trước khi quyết — ý của họ thường giúp cải thiện kết quả.',
      'Cả hai: Đổi mới của ENTP + triển khai của ESTJ = một sự kết hợp hiếm mà thật sự ra kết quả.',
    ],
    funFact: 'ENTP và ESTJ đều hướng ngoại — bộc trực và thẳng, tạo nên một nhịp tương tác hiệu quả bất ngờ (dù căng). [S]',
    coverage: 'full',
  },
  'ENTP+ESTP': {
    pairKey: 'ENTP+ESTP',
    tenCap: 'Cùng tần số',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều nghĩ nhanh và linh hoạt — dễ theo kịp nhau.',
    vungDeHop: 'Hợp về năng lượng cao — cả hai yêu hành động, tranh luận, và cái mới.',
    vungMaSat: 'Cả hai đều đi tìm sự kích thích — ai sẽ giữ ổn định khi cần? Cả hai nghĩ nhanh và bạo — dễ ganh nhau xem cách của ai thắng.',
    canDeY: [
      'Chủ động tạo ra những khoảnh khắc "lắng lại" giữa các hoạt động.',
      'Cả hai ganh nhau → tranh luận xem ai đúng.',
      'Không ai tự nhiên lo phần hậu cần thực tế.',
    ],
    cachDiQua: [
      'ENTP: Tôn trọng hiểu biết thực tế của ESTP — dữ liệu thực địa bổ sung cho lý thuyết của bạn.',
      'ESTP: Tham gia vào phần phân tích khái niệm của ENTP — nó bắt được điều mà kinh nghiệm thực địa bỏ lỡ.',
      'Cả hai: Coi tranh luận như một môn thể thao, không phải một trận đánh — thống nhất luật trước khi vào.',
    ],
    funFact: 'ENTP và ESTP đều hướng ngoại và linh hoạt — năng lượng cao, tự phát, dễ thích nghi. Ở bên nhau tự nhiên và nhanh nhẹn. [S]',
    coverage: 'full',
  },
  'ENTP+INFJ': {
    pairKey: 'ENTP+INFJ',
    tenCap: 'Bổ sung tuyệt vời',
    texture: 'golden_pair',
    dongLuc: 'Chiều sâu và tầm nhìn của INFJ + bề rộng và sự thách thức của ENTP = một bức tranh đầy đủ về thế giới.',
    vungDeHop: 'INFJ giúp ENTP hình thành niềm tin; ENTP giúp INFJ thử thách và mài giũa niềm tin.',
    vungMaSat: 'Sự thách thức liên tục của ENTP dễ làm INFJ kiệt sức; nhu cầu bình yên của INFJ dễ làm ENTP thấy nhàm. ENTP tranh luận để khám phá ý tưởng; INFJ đôi khi thấy niềm tin của mình bị tấn công.',
    canDeY: [
      'ENTP: hãy có niềm tin chứ không chỉ tranh luận.',
      'INFJ: tham gia bằng ý tưởng, không chỉ bằng cảm xúc.',
      'ENTP tranh luận liên tục → INFJ cần khoảng lặng để nạp lại mà không có.',
      'INFJ đóng lại → ENTP thấy không còn ai để cùng bàn.',
    ],
    cachDiQua: [
      'ENTP: Phân biệt rõ khi bạn đang đóng vai phản biện và khi thật sự bất đồng — nói to lên.',
      'INFJ: Tham gia bằng ý tưởng, không phải bảo vệ bản thân — "bạn đang thách thức ý tưởng, không phải mình."',
      'Cả hai: Niềm tin mạnh là điểm mạnh của cả hai — tìm cách trân trọng cả hai, đừng dập một bên.',
    ],
    funFact: 'INFJ và ENTP có chức năng dẫn đầu phản chiếu nhau — trực giác hướng nội của INFJ cộng với khám phá hướng ngoại của ENTP tạo nên một sự cộng hưởng trí tuệ hiếm có. [R]',
    coverage: 'full',
  },
  'ENTP+INFP': {
    pairKey: 'ENTP+INFP',
    tenCap: 'Ý tưởng gặp giá trị',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều lý tưởng nhưng tiếp cận khác nhau — ENTP qua logic, INFP qua giá trị.',
    vungDeHop: 'Những cuộc trò chuyện sâu về ý nghĩa và khả năng — kết nối cả trí tuệ lẫn cảm xúc.',
    vungMaSat: 'ENTP tranh luận cho vui; INFP coi ý tưởng là chuyện cá nhân — cần thận trọng về thời điểm nên đẩy. ENTP tranh luận với sự tách bạch; INFP gắn chặt với giá trị và ý tưởng — ENTP có thể vô tình làm INFP tổn thương khi thách thức điều INFP coi là cốt lõi của bản thân.',
    canDeY: [
      'ENTP: báo hiệu khi bạn đang đóng vai phản biện so với khi thật sự bất đồng.',
      'ENTP đẩy tranh luận quá đà → INFP thấy giá trị cốt lõi của mình bị công kích.', // [SỬA LỖI LẪN TYPE: gốc "INTJ… → ESFP…"]
      'INFP im lặng rút lui → ENTP không hiểu mình đã chạm vào đâu.', // [SỬA LỖI LẪN TYPE: gốc "ESFP… → INTJ…"]
    ],
    cachDiQua: [
      'ENTP: Phân biệt khi bạn đang khám phá và khi thật sự bất đồng — với INFP cần thêm sự rõ ràng, vì họ không tách ý tưởng khỏi con người mình.',
      'INFP: Tập tách "ý tưởng của mình" khỏi "mình" — ENTP thách thức ý tưởng của bạn không có nghĩa họ chối bỏ bạn.',
      'Cả hai: Cả hai đều lý tưởng — khi đồng điệu về mục đích, hai người có thể cùng tạo ra điều rất ý nghĩa.',
    ],
    funFact: 'ENTP và INFP đều có chức năng khám phá khả năng dẫn đầu — cả hai yêu việc nhìn ra các khả năng và mẫu hình, chỉ là ENTP qua logic còn INFP qua giá trị. [S]',
    coverage: 'full',
  },
  'ENTP+INTJ': {
    pairKey: 'ENTP+INTJ',
    tenCap: 'Bộ óc gặp nhau',
    texture: 'golden_pair',
    dongLuc: 'Cả hai đều chiến lược và yêu những ý tưởng phức tạp — nể nhau về trí tuệ từ sớm.',
    vungDeHop: 'INTJ mang sự tập trung và theo đến cùng; ENTP mang bề rộng và sáng tạo — một sự kết hợp mạnh.',
    vungMaSat: 'INTJ muốn chốt và đi tiếp; ENTP muốn khám phá tiếp — căng nhau về việc chốt.',
    canDeY: [
      'Đặt hạn cho quyết định — "Mình có đến [ngày] để khám phá, sau đó chốt và bắt tay làm."',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTP+INTP': {
    pairKey: 'ENTP+INTP',
    tenCap: 'Cùng thế giới',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều yêu khám phá ý tưởng và hệ thống — kết nối trí tuệ sâu.',
    vungDeHop: 'Trò chuyện không bao giờ cạn ý tưởng — luôn có điều gì đó thú vị để khám phá.',
    vungMaSat: 'Cả hai đều né vùng cảm xúc — mối quan hệ có thể quá thiên trí tuệ và thiếu hơi ấm.',
    canDeY: [
      'Sắp lịch cho những hoạt động "không trí tuệ" — cơ thể, sự hiện diện, không chỉ cái đầu.',
    ],
    cachDiQua: [],
    coverage: 'compat-only',
  },
  'ENTP+ISFJ': {
    pairKey: 'ENTP+ISFJ',
    tenCap: 'Cần nhiều cầu nối',
    texture: 'challenge_pair',
    dongLuc: 'ENTP thách thức nề nếp; ISFJ gìn giữ nề nếp — va chạm nền tảng về cách nhìn thế giới.',
    vungDeHop: 'ISFJ mang sự ổn định và chăm sóc; ENTP mang sự hào hứng và phát triển.',
    vungMaSat: 'ENTP có thể vô tình phủ nhận điều ISFJ coi trọng; ISFJ thấy chông chênh. ENTP thách thức nề nếp ISFJ coi trọng — nghe như thiếu tôn trọng ngay cả khi thuần túy là chuyện trí tuệ.',
    canDeY: [
      'ENTP: nói rõ sự trân trọng dành cho sự chăm sóc của ISFJ.',
      'ISFJ: thử tham gia một ý tưởng của ENTP.',
      'ENTP tranh luận về những nề nếp ISFJ trân trọng.',
      'Nhu cầu ổn định của ISFJ va với nhu cầu phá cách của ENTP.',
    ],
    cachDiQua: [
      'ENTP: Báo hiệu khi tranh luận cho vui so với khi thật sự đặt câu hỏi — ISFJ coi việc thách thức nề nếp là công kích cá nhân.',
      'ISFJ: Việc ENTP để tâm tới nề nếp của bạn nghĩa là họ coi trọng nó.',
      'Cả hai: Ý tưởng của ENTP + sự ấm áp của ISFJ = một cộng đồng vừa sống động về trí tuệ vừa quan tâm sâu sắc.',
    ],
    funFact: 'ENTP và ISFJ đều có chức năng dựa trên kinh nghiệm quá khứ — một bên dùng nó để phản biện (ENTP), một bên dùng nó làm nền tảng (ISFJ). [S]',
    coverage: 'full',
  },
  'ENTP+ISFP': {
    pairKey: 'ENTP+ISFP',
    tenCap: 'Khác nhưng hút nhau',
    texture: 'challenge_pair',
    dongLuc: 'Trí tuệ của ENTP làm ISFP tò mò; sự chân thật của ISFP làm ENTP tò mò — tò mò lẫn nhau.',
    vungDeHop: 'ISFP kéo ENTP về với hiện tại và giác quan; ENTP mở ISFP tới những ý tưởng mới.',
    vungMaSat: 'Lối tranh luận của ENTP dễ làm ISFP dịu dàng quá tải; sự rút lui của ISFP dễ làm ENTP bực. ENTP tranh luận ý tưởng với sự tách bạch; ISFP giữ giá trị một cách cá nhân — ENTP có thể làm tổn thương mà không nhận ra.',
    canDeY: [
      'ENTP: giảm cường độ khi ở cạnh ISFP.',
      'ISFP: chia sẻ chính kiến nhiều hơn — ENTP muốn nghe.',
      'ENTP tranh luận về giá trị cốt lõi của ISFP như một bài tập trí tuệ.',
      'Sự lặng lẽ rút lui của ISFP làm ENTP bối rối.',
    ],
    cachDiQua: [
      'ENTP: Giá trị cốt lõi của ISFP không phải để đem ra tranh luận — tách ý tưởng khỏi bản sắc của họ.',
      'ISFP: Nói ra khi ENTP vượt qua một ranh giới cá nhân — họ thật sự không biết ranh giới đó ở đâu.',
      'Cả hai: Khả năng của ENTP + sự chân thật của ISFP = những ý tưởng vừa hứng thú vừa có thật.',
    ],
    funFact: 'ENTP và ISFP đều thuộc nhóm linh hoạt — sự cởi mở với trải nghiệm tạo nhiều điểm chung hơn ta tưởng. [S]',
    coverage: 'full',
  },
  'ENTP+ISTJ': {
    pairKey: 'ENTP+ISTJ',
    tenCap: 'Khác cơ bản',
    texture: 'challenge_pair',
    dongLuc: 'ENTP sống nhờ phá vỡ nếp cũ; ISTJ sống nhờ sự ổn định — hai nhu cầu đối nghịch.',
    vungDeHop: 'ISTJ mang sự đáng tin; ENTP mang sự đổi mới — nếu họ tôn trọng nhau.',
    vungMaSat: 'ENTP thấy ISTJ nhàm; ISTJ thấy ENTP thiếu trách nhiệm — dễ phán xét lẫn nhau. ENTP phá cách; ISTJ giữ ổn định — va chạm nền tảng về việc thay đổi có phải là cải thiện hay không.',
    canDeY: [
      'Tìm MỘT việc để cùng làm — chứng minh hai người làm việc được với nhau bất chấp khác biệt.',
      'ENTP thách thức những cách ISTJ đã chứng minh là hiệu quả.',
      'Sự cứng nhắc của ISTJ ngăn khâu phát triển mà ENTP khởi xướng.',
    ],
    cachDiQua: [
      'ENTP: Chứng minh phương án thay thế hiệu quả trước khi gạt bỏ cách đã kiểm chứng — ISTJ cần bằng chứng.',
      'ISTJ: Thử một đề xuất thay đổi của ENTP kèm thời gian đánh giá — dữ liệu hơn giả định.',
      'Cả hai: Đổi mới của ENTP + sự đáng tin của ISTJ = những thay đổi thật sự trụ được.',
    ],
    funFact: 'ENTP và ISTJ đều có tư duy hướng ngoại trong cấu trúc — cùng tôn trọng những hệ thống hiệu quả, dù bất đồng về hệ thống nào. [S]',
    coverage: 'full',
  },
  'ENTP+ISTP': {
    pairKey: 'ENTP+ISTP',
    tenCap: 'Tôn trọng thực chất',
    texture: 'growth_pair',
    dongLuc: 'Cả hai đều giỏi và thiên logic — nể nhau về trí tuệ và kỹ năng thực tế.',
    vungDeHop: 'ISTP mang năng lực làm thực tế; ENTP mang tư duy chiến lược — khác nhau nhưng bổ sung.',
    vungMaSat: 'ENTP muốn bàn về ý tưởng; ISTP chỉ muốn bắt tay làm — lệch nhau về phong cách giao tiếp. ENTP tranh luận theo lý thuyết; ISTP tập trung vào thực tế — khác nhau về mức độ trừu tượng nên dễ va.',
    canDeY: [
      'Luân phiên: lúc thì bàn về nó (kiểu ENTP), lúc thì cứ làm (kiểu ISTP).',
      'Những điều trừu tượng lý thuyết của ENTP làm ISTP thực tế thấy nhàm.',
      'Sự tập trung vào cái cụ thể của ISTP giới hạn những khám phá khái niệm của ENTP.',
    ],
    cachDiQua: [
      'ENTP: Đặt lý thuyết vào thực tế của ISTP — "Điều này sẽ chạy thế nào trong thực tế?" là câu hỏi đúng.',
      'ISTP: Đôi khi tham gia vào các khái niệm của ENTP — lý thuyết đôi khi đoán trước được điều mà kinh nghiệm chưa thấy.',
      'Cả hai: Hai người lý trí — một lý thuyết, một thực tế — bổ sung trí tuệ hiếm có khi kết nối được.',
    ],
    funFact: 'ENTP và ISTP đều thiên lý trí và linh hoạt — cả hai đều ghét bị bảo phải làm gì. Cùng tôn trọng sự độc lập của nhau. [S]',
    coverage: 'full',
  },
}
